Enable-worlds:
  - 'world_1'

# Es muy util si el pvp es en el mismo mundo en el que salen y entran
# Si se tiene un spawn o varios mundos de pvp es mejor desactivarlo
Data:
  Keep:
    Enable: false
    Time-Minutes: 10
  Top:
    Time-Seconds: 60

Chat:
  Hover:
    - '&aName: &f%rs_name%_n'
    - '&aKills: &f%rs_kills%_n'
    - '&aDeaths: &f%rs_deaths%_n'
    - '&aBest ks: &f%rs_bestkillstreak%_n'
    - '&aCurrent ks: &f%rs_currentkillstreak%'
  Message: '%player% > %message%'
  ColoredMessage-Permission: 'rstats.chat.coloredmessages'