name: Stats
version: ${project.version}
main: net.royalmind.stats.Stats
load: STARTUP
authors: [ImSrPanda]
description: Controlador de estadisticas
commands:
  rstats:
    usage: /stats
    description: /stats for help